---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-mem-resources
spec:
  containers:
  - name: pod-cpu-resources
    image: polinux/stress
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "150Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "120M", "--vm-hang", "1"]
...
